// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (first_name, last_name, phone_number)
VALUES ($1, $2, $3) RETURNING id, first_name, last_name, phone_number
`

type CreateUserParams struct {
	FirstName   string
	LastName    string
	PhoneNumber string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createUser, arg.FirstName, arg.LastName, arg.PhoneNumber)
}

const deactivateUser = `-- name: DeactivateUser :exec
DELETE FROM users WHERE id = $1 RETURNING id, first_name, last_name, phone_number
`

func (q *Queries) DeactivateUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, phone_number FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET first_name = $1, last_name = $2, phone_number = $3
WHERE id = $4 RETURNING id, first_name, last_name, phone_number
`

type UpdateUserParams struct {
	FirstName   string
	LastName    string
	PhoneNumber string
	ID          int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.ID,
	)
	return err
}
